load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "matmul",
    srcs = ["matmul.cc"],
    hdrs = ["matmul.h"],
    visibility = ["//main:__pkg__"],
    deps = ["//matutils:matutils"],
)
